<a href="https://colab.research.google.com/github/Dhanush2915/classifiactionmodel/blob/main/Major_project_smartknower.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy as sp
import seaborn as sns

Mounted at /content/drive


# New section

In [ ]:
path="/content/adult.csv"
df=pd.read_csv(path)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df.head()

Age          Workclass  Fnlwgt   Education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [ ]:
df.columns =["Age","Workclass","Fnlwgt","Education","education_num","marital_status","occupation","relationship","race","sex","capital_gain","capital_loss","hours_per_week","native_country","income"]

In [ ]:
df.head()

Age          Workclass  Fnlwgt   Education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

# New section

In [ ]:

df.shape

(32561, 15)

In [ ]:
df["income"].value_counts()

 <=50K    24720
 >50K      7841
Name: income, dtype: int64

In [ ]:
df.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [ ]:
df.corr()

Age    Fnlwgt  education_num  capital_gain  capital_loss  \
Age             1.000000 -0.076646       0.036527      0.077674      0.057775   
Fnlwgt         -0.076646  1.000000      -0.043195      0.000432     -0.010252   
education_num   0.036527 -0.043195       1.000000      0.122630      0.079923   
capital_gain    0.077674  0.000432       0.122630      1.000000     -0.031615   
capital_loss    0.057775 -0.010252       0.079923     -0.031615      1.000000   
hours_per_week  0.068756 -0.018768       0.148123      0.078409      0.054256   

                hours_per_week  
Age                   0.068756  
Fnlwgt               -0.018768  
education_num         0.148123  
capital_gain          0.078409  
capital_loss          0.054256  
hours_per_week        1.000000

In [ ]:
df.dtypes

Age                int64
Workclass         object
Fnlwgt             int64
Education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [ ]:
cat=[x for x in df.columns if df[x].dtype=="object"]
cat


['Workclass',
 'Education',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native_country',
 'income']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat:
  df[i]=le.fit_transform(df[i])
df.dtypes

Age               int64
Workclass         int64
Fnlwgt            int64
Education         int64
education_num     int64
marital_status    int64
occupation        int64
relationship      int64
race              int64
sex               int64
capital_gain      int64
capital_loss      int64
hours_per_week    int64
native_country    int64
income            int64
dtype: object

In [ ]:
x=df.drop(["income"],axis=1)
y=df["income"]
print(x.shape)
print(y.shape)
print(type(x))
print(type(y))

(32561, 14)
(32561,)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(26048, 14)
(6513, 14)
(26048,)
(6513,)


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [ ]:
def genmetrics(ytest,ypred):
   cm=confusion_matrix(ytest,ypred)
   print(cm)
   print("Classification report \n",classification_report(ytest,ypred))
   print("Accuracy score",accuracy_score(ytest,ypred))

In [ ]:
from sklearn.metrics import precision_score,recall_score,f1_score
def validation(ytest,ypred):
  conmatrix=confusion_matrix(ytest,ypred)
  tp=conmatrix[0][0]
  fn=conmatrix[0][1]
  fp=conmatrix[1][0]
  tn=conmatrix[1][1]
  Precision=tn/(tn+fn)
  Recall=tn/(tn+fp)
  F1_score=(2*Precision*Recall)/(Precision+Recall)
  print("Validated precision is",Precision,'\n',"Computed precision is ",precision_score(ytest,ypred))
  print("Validated recall is",Recall,'\n',"Computed recall is ",recall_score(ytest,ypred))
  print("Validated f1score is",F1_score,'\n',"Computed f1_score is ",f1_score(ytest,ypred))
  print("Accuracy is ",accuracy_score(ytest,ypred),'\n',"Computed accuracy is ",(tp+tn)/(tp+tn+fp+fn))

In [ ]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV

In [ ]:
from sklearn.tree import DecisionTreeClassifier
m1=DecisionTreeClassifier()
hparams_dectree={'criterion':['gini','entropy'],'max_depth':list(range(5,17)),'min_samples_split':list(range(10,20))}
m1_cv=RandomizedSearchCV(m1,param_distributions=hparams_dectree,scoring='accuracy')

In [ ]:
m1_cv.fit(x_train,y_train)
print(m1_cv.best_params_)

{'min_samples_split': 16, 'max_depth': 9, 'criterion': 'gini'}


In [ ]:
ypred_m1_cv=m1_cv.predict(x_test)

In [ ]:
from sklearn.metrics import precision_score
print("Training score",m1_cv.score(x_train,y_train))
print("Testing score",m1_cv.score(x_test,y_test))
genmetrics(y_test,ypred_m1_cv)
validation(y_test,ypred_m1_cv)

Training score 0.8645961302211302
Testing score 0.8539843390142792
[[4532  413]
 [ 538 1030]]
Classification report 
               precision    recall  f1-score   support

           0       0.89      0.92      0.91      4945
           1       0.71      0.66      0.68      1568

    accuracy                           0.85      6513
   macro avg       0.80      0.79      0.79      6513
weighted avg       0.85      0.85      0.85      6513

Accuracy score 0.8539843390142792
Validated precision is 0.7137907137907138 
 Computed precision is  0.7137907137907138
Validated recall is 0.6568877551020408 
 Computed recall is  0.6568877551020408
Validated f1score is 0.6841580870142809 
 Computed f1_score is  0.6841580870142809
Accuracy is  0.8539843390142792 
 Computed accuracy is  0.8539843390142792


In [ ]:
from sklearn.ensemble import RandomForestClassifier
m2=RandomForestClassifier()
hparams_randfor={'n_estimators':[50,60,70,80,100],'criterion':['gini','entropy'],'max_depth':list(range(10,20)),'min_samples_split':list(range(15,20))}
m2_cv=RandomizedSearchCV(m2,param_distributions=hparams_randfor,scoring='accuracy')

In [ ]:
m2_cv.fit(x_train,y_train)
print(m2_cv.best_params_)

{'n_estimators': 80, 'min_samples_split': 16, 'max_depth': 19, 'criterion': 'entropy'}


In [ ]:
ypred_m2_cv=m2_cv.predict(x_test)

In [ ]:
print("Training score",m2_cv.score(x_train,y_train))
print("Testing score",m2_cv.score(x_test,y_test))
genmetrics(y_test,ypred_m2_cv)
validation(y_test,ypred_m2_cv)

Training score 0.9025644963144963
Testing score 0.8670351604483341
[[4674  271]
 [ 595  973]]
Classification report 
               precision    recall  f1-score   support

           0       0.89      0.95      0.92      4945
           1       0.78      0.62      0.69      1568

    accuracy                           0.87      6513
   macro avg       0.83      0.78      0.80      6513
weighted avg       0.86      0.87      0.86      6513

Accuracy score 0.8670351604483341
Validated precision is  0.7821543408360129 
 Computed precision is  0.7821543408360129
Validated recall is  0.6205357142857143 
 Computed recall is  0.6205357142857143
Validated f1score is  0.6920341394025605 
 Computed f1_score is  0.6920341394025605
Accuracy is  0.8670351604483341 
 Computed accuracy is  0.8670351604483341


In [ ]:
from sklearn.linear_model import LogisticRegression
m3=LogisticRegression()
#hparams_logreg={'solver':['newton-cg', 'lbfgs', 'liblinear'],'penalty':['none', 'l1', 'l2', 'elasticnet']}
#m3_cv=RandomizedSearchCV(m3,param_distributions=hparams_logreg,scoring='accuracy')
m3_cv=m3

In [ ]:
m3_cv.fit(x_train,y_train)
#print(m3_cv.best_params_)

LogisticRegression()

In [ ]:
ypred_m3_cv=m3_cv.predict(x_test)

In [ ]:
print("Training score",m3_cv.score(x_train,y_train))
print("Testing score",m3_cv.score(x_test,y_test))
genmetrics(y_test,ypred_m3_cv)
validation(y_test,ypred_m3_cv)

Training score 0.7873157248157249
Testing score 0.7899585444495624
[[4672  273]
 [1095  473]]
Classification report 
               precision    recall  f1-score   support

           0       0.81      0.94      0.87      4945
           1       0.63      0.30      0.41      1568

    accuracy                           0.79      6513
   macro avg       0.72      0.62      0.64      6513
weighted avg       0.77      0.79      0.76      6513

Accuracy score 0.7899585444495624
Validated precision is 0.6340482573726541 
 Computed precision is  0.6340482573726541
Validated recall is 0.30165816326530615 
 Computed recall is  0.30165816326530615
Validated f1score is 0.4088159031979257 
 Computed f1_score is  0.4088159031979257
Accuracy is  0.7899585444495624 
 Computed accuracy is  0.7899585444495624


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
m4=KNeighborsClassifier()
hparams_knn={'n_neighbors':[1,3,5,7,9,11,13,15,17,19,21,23,25]}
m4_cv=GridSearchCV(m4,hparams_knn,scoring='accuracy')

In [ ]:
m4_cv.fit(x_train,y_train)
print(m4_cv.best_params_)

{'n_neighbors': 23}


In [ ]:
ypred_m4_cv=m4_cv.predict(x_test)

In [ ]:
print("Training score",m4_cv.score(x_train,y_train))
print("Testing score",m4_cv.score(x_test,y_test))
genmetrics(y_test,ypred_m4_cv)
validation(y_test,ypred_m4_cv)

Training score 0.8028639434889435
Testing score 0.8003992015968064
[[4873   72]
 [1228  340]]
Classification report 
               precision    recall  f1-score   support

           0       0.80      0.99      0.88      4945
           1       0.83      0.22      0.34      1568

    accuracy                           0.80      6513
   macro avg       0.81      0.60      0.61      6513
weighted avg       0.81      0.80      0.75      6513

Accuracy score 0.8003992015968064
Validated precision is 0.8252427184466019 
 Computed precision is  0.8252427184466019
Validated recall is 0.21683673469387754 
 Computed recall is  0.21683673469387754
Validated f1score is 0.34343434343434337 
 Computed f1_score is  0.34343434343434337
Accuracy is  0.8003992015968064 
 Computed accuracy is  0.8003992015968064


In [ ]:
from sklearn.svm import SVC
m5=SVC(kernel='linear')

In [ ]:
m5.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
ypred_m5=m5.predict(x_test)

In [ ]:
print("Training score",m5.score(x_train,y_train))
print("Testing score",m5.score(x_test,y_test))
genmetrics(y_test,ypred_m5)
validation(y_test,ypred_m5)

Training score 0.7967982186732187
Testing score 0.799324428066943
[[4707  238]
 [1069  499]]
Classification report 
               precision    recall  f1-score   support

           0       0.81      0.95      0.88      4945
           1       0.68      0.32      0.43      1568

    accuracy                           0.80      6513
   macro avg       0.75      0.64      0.66      6513
weighted avg       0.78      0.80      0.77      6513

Accuracy score 0.799324428066943
Validated precision is 0.6770691994572592 
 Computed precision is  0.6770691994572592
Validated recall is 0.3182397959183674 
 Computed recall is  0.3182397959183674
Validated f1score is 0.4329718004338395 
 Computed f1_score is  0.4329718004338395
Accuracy is  0.799324428066943 
 Computed accuracy is  0.799324428066943


In [ ]:
accuracies={"Decision tree":accuracy_score(y_test,ypred_m1_cv),"Random Forest":accuracy_score(y_test,ypred_m2_cv),"Logistic Regression":accuracy_score(y_test,ypred_m3_cv),"KNN":accuracy_score(y_test,ypred_m4_cv),"SVM":accuracy_score(y_test,ypred_m5)}
key_list=list(accuracies.keys())
value_list=list(accuracies.values())
value=max(value_list)
print("The most accurate model is",key_list[value_list.index(value)],"with accuracy",value)

The most accurate model is Random Forest with accuracy 0.8670351604483341
